<a href="https://colab.research.google.com/github/JacqueDominguez/joyitas_de_python/blob/main/Merge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

Creamos los Dataframes

In [22]:
# Create Population DataFrame
df1 = pd.DataFrame({
    'Country': ['America', 'Indonesia', 'France', 'Italy'],
    'Location': ['New York', 'Jakarta', 'Paris','Rome'],
    'Population': [731800, 575030, 183305, 159863]
})

# Create Income DataFrame
df2 = pd.DataFrame({
    'Countries': ['America', 'America', 'Indonesia', 'India', 'France', 'Greece'],
    'Location': ['New York', 'Chicago', 'Jakarta', 'Mumbai', 'Paris', 'Yunani'],
    'Income': [1000, 1500, 1400, 1100, 900, 1200]

})

Combinamos ambas tablas con Full Outer Join y le creamos una nueva columna con el resultado

In [24]:
merge = pd.merge(df1, df2 , how='outer', indicator='resultado',sort=True, left_on='Country', right_on='Countries')

Ahora el resultado lo pueden obsevar en la columna "RESULTADO"

* both = el dato está en los DOS data frames
* left_only = el dato sólo está en el DF1
* right_only = el dato sólo está en el DF2

Para ver las diferencias filtramos en la columna rsultado los elementos que SÓLO están en el DF1 y NO están en el DF2 - LEFT JOIN IF NULL

In [25]:
merge[merge.resultado=='left_only']

  Country Location_x  Population Countries Location_y  Income  resultado
6   Italy       Rome    159863.0       NaN        NaN     NaN  left_only

Para ver las diferencias filtramos los elementos que SÓLO están en el DF2 y NO están en el DF1 - RIGHT JOIN IF NULL

In [26]:
merge[merge.resultado=='right_only']

  Country Location_x  Population Countries Location_y  Income   resultado
3     NaN        NaN         NaN    Greece     Yunani  1200.0  right_only
4     NaN        NaN         NaN     India     Mumbai  1100.0  right_only

Vemos las columnas que coinciden - INNER JOIN

In [27]:
merge[merge.resultado=='both']

     Country Location_x  Population  Countries Location_y  Income resultado
0    America   New York    731800.0    America   New York  1000.0      both
1    America   New York    731800.0    America    Chicago  1500.0      both
2     France      Paris    183305.0     France      Paris   900.0      both
5  Indonesia    Jakarta    575030.0  Indonesia    Jakarta  1400.0      both

LEFT JOIN

In [29]:
left = pd.merge(df1, df2 , how='left',sort=True, left_on='Country', right_on='Countries')

In [30]:
left

     Country Location_x  Population  Countries Location_y  Income
0    America   New York      731800    America   New York  1000.0
1    America   New York      731800    America    Chicago  1500.0
2     France      Paris      183305     France      Paris   900.0
3  Indonesia    Jakarta      575030  Indonesia    Jakarta  1400.0
4      Italy       Rome      159863        NaN        NaN     NaN

RIGHT JOIN

In [32]:
right = pd.merge(df1, df2 , how='right',sort=True, left_on='Country', right_on='Countries')

In [33]:
right

     Country Location_x  Population  Countries Location_y  Income
0    America   New York    731800.0    America   New York    1000
1    America   New York    731800.0    America    Chicago    1500
2     France      Paris    183305.0     France      Paris     900
3        NaN        NaN         NaN     Greece     Yunani    1200
4        NaN        NaN         NaN      India     Mumbai    1100
5  Indonesia    Jakarta    575030.0  Indonesia    Jakarta    1400